user www-data;
worker_processes 1;
pid /run/nginx-backend.pid;
include /etc/nginx/modules-enabled/*.conf;
worker_rlimit_nofile 65535;

events {
    use epoll;
    worker_connections 1000;
}

http {
    output_buffers 1 256k;
    
    aio off;
    sendfile off;
    tcp_nodelay on; 
    tcp_nopush off;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    client_body_buffer_size 64k;
    client_header_buffer_size 1k;      
    large_client_header_buffers 1 2k;  

    proxy_buffer_size 64k;
    proxy_busy_buffers_size 128k;
    proxy_buffers 4 64k;
    proxy_buffering off;


    #access_log /home/jbrelot/NEWODB/debug/access-backend.log;
    #error_log /home/jbrelot/NEWODB/debug/error-backend.log;

    server {
        listen 42002 reuseport;
        server_name 172.16.20.23;

        location / {
            root /home/jbrelot/NEWODB/rsc;
            index index.html;
        }

        location ~ \.(gif|jpg|png|txt|mp4|mp3)$ {
            root /home/jbrelot/NEWODB/rsc;
        }
    }
}