# Liste des ports sur lesquels utiliser ODB
ports = 42001 42002

#identification comme front-end
front-end = true

# Politique d’erreur distante
remote-error-strategy = best_effort

# Valeur de corruption
corrupt-value = -42

# Compte à rebours en ms
countdown = 3000

# Adresse du serveur central (avec port optionnel)
server-ip = IP_FE
server-port = 42042
# ou simplement :
# server = 192.168.0.10
